SECRET_KEY_BASE: __SECRET_KEY_BASE__
DATABASE_URL: postgres://__DB_USER__:__DB_PWD__@localhost/__DB_NAME__
RAILS_ENV: production
SMTP_ADDRESS: localhost
SMTP_DOMAIN: __DOMAIN__
SMTP_PORT: 25
SMTP_STARTTLS_AUTO: false
SMTP_AUTHENTICATION: None
QUEUE_ADAPTER: delayed_job
STORAGE_PROVIDER: local
DECIDIM_DEFAULT_LOCALE: __LANGUAGE__
DECIDIM_APPLICATION_NAME: YunoHost Decidim
DECIDIM_MAILER_SENDER: decidim@__DOMAIN__
